name: this_is_your_training
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+9

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  intl: ^0.18.0
  google_fonts: ^4.0.4
  curved_navigation_bar: ^1.0.3
  snippet_coder_utils: ^1.0.12
  cloud_firestore: ^4.3.1
  flutter_bloc: ^8.1.2
  flutter_gen: ^5.2.0
  bloc: ^8.1.2
  meta: ^1.7.0
  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^4.4.1+1
  image_picker: ^0.8.7+1
  get: ^4.6.5
  firebase_storage: ^11.2.2
  firebase_database: ^10.2.3
  provider: ^6.0.5
  like_button: ^2.0.5
  logger: ^1.4.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  pedometer: ^4.0.1
  liquid_pull_to_refresh: ^3.0.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.4
  injectable_generator: ^2.4.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"




flutter:
  uses-material-design: true
  generate: true

 
  assets:
    - images/


